- name: Metrics RPi
  hosts: rick-prime
  gather_facts: true
  vars:
    ansible_user: adminuser

  tasks:
    - name: Collect Resource Usage for Raspberry Pi
      block:
        - name: Collect CPU usage
          ansible.builtin.shell: "top -bn1 | grep 'Cpu(s)' | awk '{print $2 + $4}'"
          register: cpu_usage

        - name: Collect memory usage
          ansible.builtin.shell: "free | grep Mem | awk '{print $3/$2 * 100.0}'"
          register: mem_usage

        - name: Collect disk usage
          ansible.builtin.shell: "df -h / | grep / | awk '{ print $5 }' | sed 's/%//g'"
          register: disk_usage

    - name: Save metrics to JSON file
      ansible.builtin.copy:
        content: |
          {
            "cpu_usage": "{{ cpu_usage.stdout }}",
            "mem_usage": "{{ mem_usage.stdout }}",
            "disk_usage": "{{ disk_usage.stdout }}"
          }
        dest: /tmp/metrics.json
        mode: '0744'

- name: Execute Robot Framework Test in Remote environment
  hosts: manila-john
  gather_facts: false
  vars:
    ansible_user: adminuser

  tasks:
    - name: Copy metrics file from rick-prime to manila-john
      ansible.builtin.fetch:
        src: /tmp/metrics.json
        dest: /tmp/metrics.json
        flat: true
      delegate_to: rick-prime
      vars:
        ansible_user: rsanchez

    - name: Copy Robot Framework Test to Remote Host
      ansible.builtin.copy:
        src: rpi_resources.robot
        dest: /tmp/
        mode: '0744'

    - name: Execute Robot Framework Test
      ansible.builtin.shell: "robot -d /tmp/robot_results /tmp/rpi_resources.robot"
      args:
        chdir: /tmp
      register: robot_output

    - name: Display Robot Framework Result
      ansible.builtin.debug:
        var: robot_output.stdout_lines