---
- name: Deploy Minikube
  hosts: 192.168.0.219
  gather_facts: false
  vars_files: vars.yml

  tasks:
    # minikube-setup/playbook.yml
    - name: Copy k8s-semaphore to remote host
      ansible.builtin.copy:
        src: /media/ewilson/Repositories/ansible/k8s_install/k8s
        dest: "~/{{ ansible_user }}/.kube/"
        owner: "{{ ansible_user }}"
        group: "docker"
        remote_src: false
        mode: '0755'
      become: true

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      become: true

    - name: Install Docker
      ansible.builtin.apt:
        name: "{{ docker_package }}"
        state: present
      tags:
        - docker
      become: true

    - name: Install dependencies for Minikube and kubectl
      ansible.builtin.apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
        state: present
      tags:
        - dependencies
      become: true

    - name: Add user to Docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        group: docker
      become: true
      tags:
        - docker

    - name: Install kubectl
      ansible.builtin.get_url:
        url: "https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/amd64/kubectl"
        dest: "/usr/local/bin/kubectl"
        mode: '0755'
      tags:
        - kubectl
      become: true

    - name: Verify kubectl installation
      ansible.builtin.command: kubectl version --client
      register: kubectl_version_output
      changed_when: false
      become: true

    - name: Print kubectl version
      ansible.builtin.debug:
        msg: "{{ kubectl_version_output.stdout }}"

    - name: Install Minikube
      ansible.builtin.get_url:
        url: "https://storage.googleapis.com/minikube/releases/{{ minikube_version }}/minikube-linux-amd64"
        dest: "/usr/local/bin/minikube"
        mode: '0755'
      tags:
        - minikube
      become: true

    - name: Verify Minikube installation
      ansible.builtin.command: minikube version
      register: minikube_version_output
      changed_when: false

    - name: Print Minikube version
      ansible.builtin.debug:
        msg: "{{ minikube_version_output.stdout }}"

    - name: Start Minikube
      ansible.builtin.command: minikube version
      register: minikube_version_output
      changed_when: false
      become: false

    - name: Print Minikube start output
      ansible.builtin.debug:
        msg: "{{ minikube_version_output.stdout }}"

    - name: Set kubeconfig path for kubectl
      ansible.builtin.command: "minikube config > ~/{{ ansible_user }}/.kube/config"
      tags:
        - kubeconfig
      changed_when: true

    - name: Apply PostgreSQL Persistent Volume Claim
      kubernetes.core.k8s:
        kubeconfig: ~/.kube/config
        state: present
        src: k8s/postgres/postgres-pvc.yaml
      tags:
        - k8s

    - name: Apply PostgreSQL Deployment
      kubernetes.core.k8s:
        kubeconfig: ~/.kube/config
        state: present
        src: k8s/postgres/postgres-deployment.yaml
      tags:
        - k8s

    - name: Apply PostgreSQL Service
      kubernetes.core.k8s:
        kubeconfig: ~/.kube/config
        state: present
        src: k8s/postgres/postgres-service.yaml
      tags:
        - k8s

    - name: Apply Semaphore Deployment
      kubernetes.core.k8s:
        kubeconfig: ~/.kube/config
        state: present
        src: k8s/semaphore/semaphore-deployment.yaml
      tags:
        - k8s

    - name: Apply Semaphore Service
      kubernetes.core.k8s:
        kubeconfig: ~/.kube/config
        state: present
        src: k8s/semaphore/semaphore-service.yaml
      tags:
        - k8s
