---
- name: "Print localhost facts"
  hosts: localhost
  gather_facts: true  # Enable fact gathering
  tasks:
    - name: "Display all localhost facts"
      ansible.builtin.debug:
        var: ansible_facts  # This will print all gathered facts
