---
- name: Reboot RPI
  hosts: 192.168.0.72
  gather_facts: false
  become: true
  become_user: root
  vars:
    ansible_user: rsanchez

  tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      ansible.builtin.apt:
        update_cache: yes
      register: apt_update
    
    - debug:
        var: apt_update
    
    - name: Upgrade the OS (apt-get dist-upgrade)
      ansible.builtin.apt:
        upgrade: dist
      register: apt_upgrade

    - debug:
        var: apt_upgrade
        
    - name: Reboot RPI
      ansible.builtin.reboot:
      register: reboot_stat

    - debug:
        var: reboot_stat
