---
- name: Install Robot Framework
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Install Python3-pip
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: true

    - name: Install Robot Framework and JSONLibrary
      ansible.builtin.pip:
        name:
          - robotframework
          - robotframework-jsonlibrary
        executable: /usr/bin/pip3
        state: present
      register: pip_result
