# Create app User
- name: Create app user group
  ansible.builtin.group:
    name: "{{ app_group }}"
    state: present

- name: Create app user
  ansible.builtin.user:
    name: "{{ app_username }}"
    group: "{{ app_group }}"
    shell: /sbin/nologin
    create_home: false
    state: present
